services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '1000:1000'
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - mynetwork
  
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./app/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
  gcs:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - ${PWD}/tmp/gcs-data:/data/images
    command: -scheme http
    networks:
      - mynetwork

volumes:
  db-data:
networks:
  mynetwork:
    external: true
